#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class TextBox;
                ref class Slider;
                ref class Button;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Input {
                ref class KeyboardAccelerator;
            }
        }
    }
}

namespace VMultiUWPApp_WRC
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MyUserControl : public ::Windows::UI::Xaml::Controls::UserControl, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MyUserControl_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::TextBox^ box;
        private: ::Windows::UI::Xaml::Controls::Slider^ slider;
        private: ::Windows::UI::Xaml::Controls::Button^ button;
        private: ::Windows::UI::Xaml::Input::KeyboardAccelerator^ accelAbout;
        private: ::Windows::UI::Xaml::Input::KeyboardAccelerator^ accelExit;
    };
}

